# Site settings
title: Outflow
email: hello@outflowapp.com
description: > # this means to ignore newlines until "baseurl:"
   Subscription manager tool for iOS. Quickly view all your subscriptions in on simple and convenient place.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://outflowapp.com/" # the base hostname & protocol for your site
twitter_username: outflowapp
permalink: /blog/:title

# Build settings
markdown: kramdown
